name: website

on: push

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    name: build
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
          destination_dir: ./
